services:
  website:
    container_name: newtoncuff_website
    build:
      context: ./website
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - SQLALCHEMY_DATABASE_URI="mysql+mysqlconnector://root:Saida1986@69.48.207.125:3306/newtoncuff_com"
      - FLASK_DEBUG=1
    restart: always
    volumes:
      - ./website:/app
    ports:
      - '8081:80'
    networks:
      - newtoncuff_network
    depends_on:
      - nginx

  api:
    container_name: newtoncuff_api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI="mysql+mysqlconnector://root:Saida1986@69.48.207.125:3306/newtoncuff_com"
    ports:
      - '81:80'
    networks:
      - newtoncuff_network
    depends_on:
      - nginx

  # resume:
  #   build:
  #     context: ./resume
  #     dockerfile: Dockerfile
  #   container_name: newtoncuff_resume
  #   ports:
  #     - "5000:80"
  #   networks:
  #     - newtoncuff_network
  #   depends_on:
  #     - nginx

  redis:
    container_name: newtoncuff_redis
    build:
      context: ./redis  # Point to the redis directory
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - newtoncuff_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/newtoncuff.com:/etc/nginx/certs/live/newtoncuff.com
    networks:
      - newtoncuff_network

networks:
  newtoncuff_network:
    name: newtoncuff_network
    driver: bridge

volumes:
  redis_data: