services:
  resume-site:
    build:
      context: .
      dockerfile: Dockerfile
    # image: flask-resume-site
    container_name: flask-resume-site
    ports:
      - "5000:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - COMPOSE_BAKE=true
    restart: always
