# Use an official nginx image as the base image
FROM nginx:alpine

# Copy the Nginx configuration file
COPY nginx.dev.conf /etc/nginx/conf.d/default.conf

# Expose ports 80 and 443
EXPOSE 80
EXPOSE 443

# Start nginx
CMD ["nginx", "-g", "daemon off;"]